ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "imstack"
  site-url: "https://johnowhitaker.github.io/imstack/"
  description: "Represent an image as a stack of different sized tensors"
  twitter-card: true
  open-graph: true
  repo-branch: main
  repo-url: "https://github.com/johnowhitaker/imstack/tree/main/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/johnowhitaker/imstack/tree/main/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
