# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/imstack/',
                'doc_host': 'https://johnowhitaker.github.io',
                'git_url': 'https://github.com/johnowhitaker/imstack/tree/main/',
                'lib_path': 'imstack'},
  'syms': { 'imstack.core': { 'imstack.core.ImStack': ('core.html#imstack', 'imstack/core.py'),
                              'imstack.core.ImStack.__init__': ('core.html#__init__', 'imstack/core.py'),
                              'imstack.core.ImStack.forward': ('core.html#forward', 'imstack/core.py'),
                              'imstack.core.ImStack.plot_layers': ('core.html#plot_layers', 'imstack/core.py'),
                              'imstack.core.ImStack.preview': ('core.html#preview', 'imstack/core.py'),
                              'imstack.core.ImStack.preview_pil': ('core.html#preview_pil', 'imstack/core.py'),
                              'imstack.core.ImStack.save': ('core.html#save', 'imstack/core.py'),
                              'imstack.core.ImStack.to_pil': ('core.html#to_pil', 'imstack/core.py')}}}