# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ImStack": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://johnowhitaker.github.io/imstack/"

git_url = "https://github.com/johnowhitaker/imstack/tree/main/"

def custom_doc_links(name): return None
